.babelrc
.storybook/config.js
.storybook/webpack.config.js
README.md
components/helloworld.tsx
components/nav.tsx
nodemon.json
package.json
pages/index.tsx
pages/test.tsx
server/index.ts
stories/index.stories.tsx
tsconfig.json
tsconfig.server.json
yarn.lock

- Integrate storybook with typescript

Cat 2:  Integrate storybook with typescript

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md

Cat-20 [Circle CI and PR]

---

components/brands-banner-mob.tsx
pages/index.tsx

- https://solomediagroup.atlassian.net/browse/CAT-18
Create banner mobile component.

CAT-18: Create brandsBanner-mobile component

---

components/footer.tsx
layouts/main.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-21
Create main footer component.

CAT-21: Create footer

---

components/CompareEditions/CompareEditionSelect.tsx
components/CompareEditions/index.tsx
components/index.tsx
pages/products.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-27
-  Compare Edition select and description

CAT-27: Compare Edition select and description

---

components/Breadcrumb.tsx
components/index.tsx
lib/styles.ts
lib/theme.ts
pages/product.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-55
- Create Breadcrumb component

Create Breadcrumb component

---

lib/models/product.ts
pages/product.tsx
static/mockdata.json

- Add product's description in mock data

Add product's description in mock data

---

components/CartItem.tsx
components/CartList.tsx
lib/ui.ts
pages/cart.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-40
- Create cart-items-list component

Create cart-items-list component

---

components/AddProduct.tsx
components/CartItem.tsx
components/CartList.tsx
components/SuggestProductsList.tsx
components/index.tsx
lib/ui.ts
pages/cart.tsx

- https://solomediagroup.atlassian.net/browse/CAT-41
- Create add-product component

Create add-product component

---

components/AddProduct.tsx
components/CartItem.tsx
components/SuggestProductsList.tsx
lib/models/product.ts
pages/cart.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-42
- Create suggest-products-list component

Create suggest-products-list component

---

.babelrc
components/AddProduct.tsx
components/CartItem.tsx
components/CartList.tsx
components/CartTotal.tsx
components/QuantitySelect.tsx
components/SuggestProductsList.tsx
components/index.tsx
contexts/CartContext.tsx
lib/theme.ts
lib/ui.ts
pages/cart.tsx
static/mockdata.json

https://solomediagroup.atlassian.net/browse/CAT-43
Create cart context, create card-total component

Create cart context, create card-total component

---

pages/cart.tsx

https://solomediagroup.atlassian.net/browse/CAT-44
- Add reviews component in cart's page

Add reviews component in cart's page

---

components/Header/searchbar.tsx
components/SubscribeForm.tsx
components/index.tsx
lib/theme.ts
lib/ui.ts
pages/cart.tsx

- https://solomediagroup.atlassian.net/browse/CAT-45
- Create SubscribeForm component

Create SubscribeForm component

---

components/CompareEditions/CompareEditionsSelect.tsx
components/CompareEditions/CompareEditionsTable.tsx
components/CompareEditions/ProductTitle.tsx
components/CompareEditions/index.tsx
components/ProductSummary/index.tsx
lib/ui.ts
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-28
- Compare Versions Table
-  Product Summary font size fix

CAT-28: Compare Table [Category]

---

components/ProductCompareEditions/Select.tsx
components/ProductCompareEditions/Table.tsx
components/ProductCompareEditions/Title.tsx
components/ProductCompareEditions/index.tsx
components/index.tsx
pages/product.tsx
pages/products.tsx

- https://solomediagroup.atlassian.net/browse/CAT-35
- Add Compare Table to Product 
- Clear file names

CAT-35: Product Compare Table [Product]

---

components/ProductsList.tsx
pages/products.tsx
pages/search.tsx

- https://solomediagroup.atlassian.net/browse/CAT-24
- Add products list to categories page

Add products list to categories page

---

.babelrc
lib/apolloInit.ts
lib/constants.ts
lib/services/cartsMineService.ts
lib/services/magentoApi.ts
package.json
yarn.lock

- https://solomediagroup.atlassian.net/browse/CAT-58
-  create services module, create http client to handle magento-rest-api

create services module, create http client to handle magento-rest-api

---

components/Category/CategoryItem.tsx
components/Category/index.tsx

- https://solomediagroup.atlassian.net/browse/CAT-57
-  Fix Category Item in mobile breakpoints

CAT-57:  Fix categories grid in mobile view at the home page.

---

components/Header/index.tsx
components/Header/nav-item.tsx
components/Header/nav.tsx
components/Header/submenu.tsx
hoc/defaultPage.tsx
layouts/main.tsx
lib/constants.ts
lib/services/cartsService.ts
lib/services/categoriesService.ts
lib/services/customerService.ts
lib/services/magentoApi.ts
pages/cart.tsx
pages/index.tsx
pages/product.tsx
pages/products.tsx
pages/search.tsx

- https://solomediagroup.atlassian.net/browse/CAT-59
- Set categories in main nav, set global context in defaultPage hoc

CAT-59: Set categories in main nav, set global context in defaultPage hoc

---

components/CategoriesSideBar.tsx
components/Header/index.tsx
components/Header/nav-item.tsx
components/Header/nav.tsx
components/Header/submenu.tsx
components/RadioFilterList.tsx
hoc/defaultPage.tsx
layouts/main.tsx
lib/services/productsService.ts
pages/_app.tsx
pages/index.tsx
pages/products.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-69
- Connect categories page to api.

connect categories page to api

---

components/ProductCompare/Select.tsx
components/ProductCompare/index.tsx

- https://solomediagroup.atlassian.net/browse/CAT-48
- Product Compare Select

Cat-48: Compare Filters

---

components/ProductCard.tsx
components/ProductDetail.tsx
lib/services/productsService.ts
lib/ui.ts
pages/_app.tsx
pages/product.tsx

https://solomediagroup.atlassian.net/browse/CAT-63

Connect product-detail page to api

---

components/Header/nav-item.tsx
components/Header/nav.tsx
components/Header/submenu.tsx
components/ProductCompare/Select.tsx
components/ProductCompare/Title.tsx
components/ProductCompare/index.tsx
pages/compare.tsx

- https://solomediagroup.atlassian.net/browse/CAT-75
- Comparison API connection
- Hide Comparison nav option in mobile

Comparison API connection

---

components/CartItem.tsx
components/CartList.tsx
components/CartTotal.tsx
components/Header/cta.tsx
components/Header/index.tsx
components/ProductCard.tsx
components/ProductDetail.tsx
contexts/CartContext.tsx
hoc/defaultPage.tsx
lib/constants.ts
lib/services/cartsService.ts
lib/services/magentoApi.ts
pages/cart.tsx
pages/product.tsx

https://solomediagroup.atlassian.net/browse/CAT-65
- Set cart-flow with api

Set cart-flow with api

---

components/ProductCompare/Details.tsx
components/ProductCompare/index.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-49
- Insert missing data 
- Product Compare Details

CAT-49:  Product [Compare]

---

components/Header/searchbar.tsx
lib/services/productsService.ts
pages/search.tsx

- https://solomediagroup.atlassian.net/browse/CAT-61
- trigger search with api

trigger search with api

---

pages/search.tsx

- https://solomediagroup.atlassian.net/browse/CAT-62
- pass api data to search page

pass api data to search page

---

components/Header/nav-item.tsx
components/Header/nav.tsx
components/Header/submenu.tsx
components/ProductCompare/SectionTitle.tsx
components/ProductCompare/SoftwareIncluded.tsx
components/ProductCompare/index.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-50
- Software Compare
- Navbar fix

CAT-50: Software [Compare]

---

components/Header/nav-item.tsx
components/Header/nav.tsx
components/Header/submenu.tsx
components/ProductCompare/License.tsx
components/ProductCompare/SectionTitle.tsx
components/ProductCompare/SoftwareIncluded.tsx
components/ProductCompare/index.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-51
- Product Compare License

CAT-51:  License and Instalations [Compare]

---

components/ProductCompare/Details.tsx
components/ProductCompare/Platform.tsx
components/ProductCompare/index.tsx
static/mockdata.json

- https://solomediagroup.atlassian.net/browse/CAT-52
- Product Compare Platform

CAT-52: Platform [Compare]

---

components/Header/nav-item.tsx
components/ProductCompare/Details.tsx
components/ProductCompare/Price.tsx
components/ProductCompare/Title.tsx
components/ProductCompare/index.tsx

- https://solomediagroup.atlassian.net/browse/CAT-53
- Navbar fix
- Product Compare Price

CAT-53:  Price [Compare]
